[package]
name = "baelyks-notification-daemon"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baelyks-shell-lib.workspace = true
measuring-container.workspace = true
zbus.workspace = true
freedesktop-icons.workspace = true
tokio.workspace = true
chrono.workspace = true
serde.workspace = true
freedesktop-desktop-entry.workspace = true
derive_more.workspace = true
image.workspace = true
rand.workspace = true
log.workspace = true
fern.workspace = true
clap.workspace = true
dirs.workspace = true
iced.workspace = true
iced_layershell.workspace = true
nom.workspace = true
bitflags.workspace = true
