[package]
name = "baelyks-launcher"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baelyks-shell-lib.workspace = true
clap.workspace = true
freedesktop-desktop-entry.workspace = true
iced.workspace = true
iced_layershell.workspace = true
log.workspace = true
nucleo = "0.5.0"
tokio.workspace = true
derive_more.workspace = true
walkdir.workspace = true
mime_guess.workspace = true
