[package]
name = "baelyks-shell-lib"
edition = "2024"
version.workspace = true

[dependencies]
chrono.workspace = true
fern.workspace = true
freedesktop-desktop-entry.workspace = true
freedesktop-icons.workspace = true
image.workspace = true
lazy_static.workspace = true
log.workspace = true
rand.workspace = true
system-tray.workspace = true
