[package]
name = "baelyks-bar"
version = "0.1.0"
edition = "2024"

[dependencies]
baelyks-shell-lib.workspace = true
iced.workspace = true
iced_layershell.workspace = true
chrono.workspace = true
log.workspace = true
fern.workspace = true
dirs.workspace = true
swayipc-async.workspace = true
starship-battery.workspace = true
tokio.workspace = true
system-tray.workspace = true
image.workspace = true
rand.workspace = true
freedesktop-icons.workspace = true
sysinfo.workspace = true
